// <auto-generated />
using System;
using BasementBlog.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasementBlog.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240128023307_addDescription")]
    partial class addDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("BlazorBlog.Database.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Test",
                            Description = "Test",
                            ModifiedDate = new DateTime(2024, 1, 28, 10, 33, 7, 477, DateTimeKind.Local).AddTicks(9056),
                            PublishDate = new DateTime(2024, 1, 28, 10, 33, 7, 477, DateTimeKind.Local).AddTicks(9067),
                            Title = "Make the world better"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Test",
                            Description = "Test",
                            ModifiedDate = new DateTime(2024, 1, 28, 10, 33, 7, 477, DateTimeKind.Local).AddTicks(9109),
                            PublishDate = new DateTime(2024, 1, 28, 10, 33, 7, 477, DateTimeKind.Local).AddTicks(9110),
                            Title = "AI take over the world"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
